table Orders

	measure 'Total Amount' = SUM(Orders[Amount])
		formatString: #,0.00

	measure 'Current Environment' = SELECTEDVALUE(Orders[Environment])

	column Product
		dataType: string
		summarizeBy: none
		sourceColumn: Product

	column Amount
		dataType: decimal
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: Amount

	column Environment
		dataType: string
		summarizeBy: none
		sourceColumn: Environment

	partition Orders = m
		mode: import
		source =
				let
				    Source = #table(
				        type table [Product = text, Amount = Currency.Type],
				        {
				            {"Bikes", 1250.50},
				            {"Helmets", 320.00},
				            {"Gloves", 145.75}
				        }
				    ),
				    WithEnvironment = Table.AddColumn(
				        Source, "Environment", each Environment, type text
				    )
				in
				    WithEnvironment
